Workspace
steven-ossorio/slacky pull request #2
Opened 2018-07-14 22:16 UTC by steven-ossorio

Model creation and validation. Association between a user and workspace will be done within the member table.

2018-07-16 13:37 UTC, aarron-lee reviewed
Remove the fixtures and test file since those aren't being used.

2018-07-16 14:12 UTC, aarron-lee requested changes
merge migrations into a single migration, there's no need to have multiple migrations in a working branch. Messing with migrations is only bad on the main/master branch.

2018-07-16 20:50 UTC, steven-ossorio commented
Removed test folder as requested for each branch.

2018-07-17 17:16 UTC, aarron-lee approved these changes

2018-07-17 17:16 UTC, merged